### ISSUE TITLE
Module name mismatch when using "kotlinmaterialui" dependency in Kotlin-multi-platform projects with Kotlin-frontend plugin

### ISSUE THREAD

**Issue by YuriiTrofimenko** [subroh0508/kotlin-material-ui#1]
In Kotlin-multi-platform projects with the Kotlin-frontend plugin after run "gradle build" command in the file "build/classes/kotlin/js/main/kotlin-multiplatform-react.js" appeares the following code:

require('**core**')

But in the file "build/tmp/expandedArchives/core-0.2.0.jar_dcc55458032b962ff6459c2be8fb3018/package.json" appeares

"name": "**kotlin-material-ui-core**"
"main": "**kotlin/kotlin-material-ui-core.js**"

instead of

"name": "**core**"
"main": "**core.js**"

and in the directory "build/node_modules_imported" - subdirectory

"kotlin-material-ui-core"

instead of

"core"

and there, in the file "build/node_modules_imported/kotlin-material-ui-core/package.json", appeares

"name": "kotlin-material-ui-core"
"main": "kotlin/kotlin-material-ui-core.js"

instead of

"name": "core"
"main": "core.js"

This leads to the error during running "gradle run" command:

ERROR in ./kotlin-multiplatform-react.js
Module not found: Error: Can't resolve 'core' in '.../build/classes/kotlin/js/main'
 @ ./kotlin-multiplatform-react.js 3018:299-314

Manual changing incorrect values to "core" after "gradle build" before "gradle run" fixes the problem.

**Comment by subroh0508** [comment]
Use `v0.2.4`, maybe has fixed.
