### ISSUE TITLE
onNodeSelect in TreeViewProps breaks type system on single select

### ISSUE THREAD

**Issue by altavir** [subroh0508/kotlin-material-ui#24]
The event has a parameter `Array<String>`, but actually gives a single string in case of single select.

I suggest to introduce new virtual type ArrayOrSingle and combine it with dynamic type check to properly evaluate.

**Comment by subroh0508** [comment]
fix https://github.com/subroh0508/kotlin-material-ui/commit/d85b162e5016fc02bc945da6f1d7b20218f2cf51 / https://github.com/subroh0508/kotlin-material-ui/commit/9c29b8c8c6c21069da031635b5ee84d49c478176 👍

**Comment by altavir** [comment]
Now I can't access onNodeSelect at all since it is protected and could not be changed from the outside. Event if it was public, I would have to explicitly cast the builder to approprieate descendant. I think that you can't do it in a type-safe way with a single builder. You have to either leave it dynamic or to build two different builders - one for single-select mode and one for multi-select mode.

**Comment by altavir** [comment]
Fixed it for now by adding explicit type cast `this as SingleSelectTreeViewElementBuilder<UL>` in the builder.
