### ISSUE TITLE
Could not find subroh0508.net.kotlinmaterialui:date-io:0.5.0-beta2

### ISSUE THREAD

**Issue by heathwinning** [subroh0508/kotlin-material-ui#34]
While trying to update to 0.5.0, I'm getting
```
Could not find subroh0508.net.kotlinmaterialui:date-io:0.5.0-beta2
Required by:
         project : > net.subroh0508.kotlinmaterialui:pickers:0.5.0
```
upon build. Not sure if there is a typo in the dependencies or date-io hasn't been updated on bintray.

**Comment by subroh0508** [comment]
@heathwinning I have uploaded `:date-io` artifacts to bintray and requested to include the package in jcenter.
Few days later, you will be able to update on v0.5.1!

**Comment by heathwinning** [comment]
I closed this prematurely. I am still getting the same error when using `net.subroh0508.kotlinmaterialui:pickers:0.5.1`. Is it because `pickers:0.5.1` is specifically requesting `date-io:0.5.0-beta2`?

**Comment by heathwinning** [comment]
Resolved with `net.subroh0508.kotlinmaterialui:pickers:0.5.2`
