### ISSUE TITLE
Plugin [id: 'org.jetbrains.kotlin.js'] was not found in any of the following sources

### ISSUE THREAD

**Issue by 21region** [subroh0508/kotlin-material-ui#4]
![image](https://user-images.githubusercontent.com/3749557/71356403-2df9fe80-2593-11ea-998d-ea20c2b52b83.png)

**Comment by subroh0508** [comment]
@21region You use Kotlin `v1.4.0` or above?
`org.jetbrains.kotlin.js` is added since `v1.4.0`, so you encountered the error, maybe.

**Comment by subroh0508** [comment]
Sorry, I encountered same error from GUI of IntelliJ.
Please use command line, like `./gradlew :sample:browserRun`.

**Comment by subroh0508** [comment]
Fix it! It works, maybe!
