### ISSUE TITLE
Jcenter is shutting down - need to migrate to Maven Central

### ISSUE THREAD

**Issue by tlpierce** [subroh0508/kotlin-material-ui#45]
JFrog has [announced they are shutting down Jcenter and Bintray]https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). New package versions can no longer be published. The packages will continue to be hosted until Feb 1, 2022.  Unfortunately that means the project will need to migrate to Maven Central.

**Comment by subroh0508** [comment]
@tlpierce Migrating to MavenCentral has completed!

Please update `v0.5.6` with `maven(url = "https://s01.oss.sonatype.org/content/repositories/releases")` 😉
