### ISSUE TITLE
Warning: Failed prop type: Invalid prop `disabled` of type `string` supplied to `Button`, expected `boolean`.

### ISSUE THREAD

**Issue by 21region** [subroh0508/kotlin-material-ui#6]
![image](https://user-images.githubusercontent.com/3749557/71356593-c0020700-2593-11ea-85b8-5c9103238fd7.png)

webpack-internal:///../../node_modules/prop-types/checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `disabled` of type `string` supplied to `Button`, expected `boolean`.
    in Button (created by WithStyles(Button))
    in WithStyles(Button) (created by ButtonsDemo)
    in div (created by ButtonsDemo)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by ButtonsDemo)
    in ButtonsDemo (created by WithStyles(ButtonsDemo))
    in WithStyles(ButtonsDemo) (created by App)
    in div (created by App)
    in MuiThemeProviderOld (created by App)
    in App

**Comment by oxc** [comment]
I believe you're referencing the `disabled` property of BUTTON. To access the extension function provided by ButtonBaseElementBuilder, you can use `(this as Tag).disabled = true`

**Comment by subroh0508** [comment]
@oxc Thank you for teaching me! The warning has fixed! 😎
